name: Check Conventional Commits
on:
  push:
    branches:
      - *
jobs:
  checkCommits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: webiny/action-conventional-commits@v1.1.0
